language: ruby
cache: bundler

before_install: gem update --system && gem install bundler

rvm:
  - ruby-head
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - 2.1.9
  - 2.0.0

matrix:
  allow_failures:
    - rvm: ruby-head

addons:
  code_climate:
    repo_token: 0a2847375a857d42a2ac98d7ffe6590f164fa9f7b42b43bab9467ab4aef6da3e

after_success:
  - bundle exec codeclimate-test-reporter
